spring:
  application:
    name: hotelchainsystem
    active: local
  profiles:
    active: local
  data:
    mongodb:
      uri: mongodb://localhost:27017/testdb?readPreference=primaryPreferred
      database: hotelchaindb
server:
  port: 8080
